/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cz.cvut.fit.compactjvm.definitions;

/**
 * Method access flags
 * @author Nick Nemame
 */
public class MethodAccessFlag {
    public static final int ACC_PUBLIC      = 0x0001;	//Declared public; may be accessed from outside its package.
    public static final int ACC_PRIVATE     = 0x0002;	//Declared private; accessible only within the defining class.
    public static final int ACC_PROTECTED   = 0x0004;	//Declared protected; may be accessed within subclasses.
    public static final int ACC_STATIC      = 0x0008;	//Declared static.
    public static final int ACC_FINAL       = 0x0010;	//Declared final; must not be overridden (§5.4.5).
    public static final int ACC_SYNCHRONIZED= 0x0020;	//Declared synchronized; invocation is wrapped by a monitor use.
    public static final int ACC_BRIDGE      = 0x0040;	//A bridge method, generated by the compiler.
    public static final int ACC_VARARGS     = 0x0080;	//Declared with variable number of arguments.
    public static final int ACC_NATIVE      = 0x0100;	//Declared native; implemented in a language other than Java.
    public static final int ACC_ABSTRACT    = 0x0400;	//Declared abstract; no implementation is provided.
    public static final int ACC_STRICT      = 0x0800;	//Declared strictfp; floating-point mode is FP-strict.
    public static final int ACC_SYNTHETIC   = 0x1000;	//Declared synthetic; not present in the source code.
}
